# Q1

In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Q2

In [17]:
l1=[]
n=int(input())
for i in range(0,n):
    el=int(input())
    l1.append(el)
print("lst1:",l1)
l2=[]
x=int(input())
for i in range(0,x):
    ele=int(input())
    l2.append(ele)
print("lst2:",l2)
print()
arr1=np.array(l1)
print("Arr1:",arr1)
arr2=np.array(l2)
print("Arr2:",arr2)
print(arr1+arr2)
print()
print(np.sort(arr1))
print(np.sort(arr2))

4
9
6
1
5
lst1: [9, 6, 1, 5]
4
7
3
2
8
lst2: [7, 3, 2, 8]

Arr1: [9 6 1 5]
Arr2: [7 3 2 8]
[16  9  3 13]

[1 5 6 9]
[2 3 7 8]


# Q3

In [18]:
arr3 = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("Array is of type: ", type(arr3))
print("No. of dimensions: ", arr3.ndim)
print("Size of array: ", arr3.size)
print("Array stores elements of type: ", arr3.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Size of array:  6
Array stores elements of type:  int32


# Q4

In [28]:
#Converting of 1D array into 2D array
arr4=np.array([1,2,3,4,5,6])
print(arr4.shape)
a=arr4[np.newaxis,:]
print(a.shape)
b=np.expand_dims(arr4,axis=0)
print(b.shape)
c=np.expand_dims(arr4,axis=1)
print(c.shape)

(6,)
(1, 6)
(1, 6)
(6, 1)


# Q5 

In [37]:
arr5=np.array([12,13,14])
arr6=np.array([21,22,23])
print("Horizontal :",np.hstack((arr5,arr6)))
print()
print("Vertical:",np.vstack((arr5,arr6)))

Horizontal : [12 13 14 21 22 23]

Vertical: [[12 13 14]
 [21 22 23]]


# Q6

In [39]:
#To get Unique items we use unique() function. The unique() function is used to find the unique elements of an array.
f = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:",f)
unique_elements, counts_elements = np.unique(f, return_counts=True)
print("Count of unique values of array:")
print(np.asarray((unique_elements, counts_elements)))

Original array: [10 10 20 10 20 20 20 30 30 50 40 40]
Count of unique values of array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
